name: Convert XMLA to BIM

on: [workflow_dispatch]

jobs:
  convert-xmla-to-bim:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Tabular Editor
        run: choco install tabular-editor -y
        shell: powershell

      - name: Generate BIM file using XMLA file
        run: |
          $xmlaPath = "${{ github.workspace }}\YourXMLAFile.xmla"  # Replace with your actual XMLA filename
          $bimPath = "${{ github.workspace }}\Model.bim"
          
          TabularEditor.exe "$xmlaPath" -B "$bimPath"
        shell: powershell

      - name: Upload BIM File as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: model-bim
          path: Model.bim
