name: Deploy Power BI Dataset (GitHub Actions)

on: [workflow_dispatch]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Bim file using XMLA file
        shell: pwsh
        run: |
          # Generate Bim file using XMLA file
          $PBIDataset = "aa.xmla"
          $BimOutput = "Model.bim"

          # Find the TabularEditor.exe file within the current directory.
          $TabularEditor = "D:\a\WKEnablon_POC\WKEnablon_POC\TabularEditor.exe" # assuming it is in the root of the repository.

          # Run TabularEditor to generate .bim file
          & $TabularEditor $PBIDataset -B $BimOutput

          # Get the full path of the created BIM file and print it.
          $FullPath = Get-Item -Path $BimOutput | Select-Object -ExpandProperty FullName
          Write-Host "BIM file created at: $FullPath"

      - name: Verify BIM file exists
        shell: pwsh
        run: |
          if (Test-Path -Path "Model.bim") {
            Write-Host "BIM file exists in the current directory."
          } else {
            Write-Error "BIM file was not created."
            exit 1 # Exit with error code if the file does not exist.
          }
