name: Deploy Power BI Dataset (GitHub Actions)

on: [workflow_dispatch]
 

jobs:
  deploy:
    runs-on: windows-latest

  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Tabular Editor
        run: |
          $TabularEditorUrl = "https://github.com/otykier/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip"
          $DownloadDestination = Join-Path (Get-Location) "TabularEditor.zip"
          Invoke-WebRequest -Uri $TabularEditorUrl -OutFile $DownloadDestination
          Expand-Archive -Path $DownloadDestination -DestinationPath (Get-Location).Path
          Remove-Item $DownloadDestination
        shell: pwsh

    
