name: Power BI Dataset Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Power BI Build Job
    runs-on: windows-latest

    steps:
      # 4. Download Tabular Editor
      - name: Download Tabular Editor
        run: |
          $TabularEditorUrl = "https://github.com/otykier/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip"
          $DownloadDestination = Join-Path (Get-Location) "TabularEditor.zip"
          Invoke-WebRequest -Uri $TabularEditorUrl -OutFile $DownloadDestination
          Expand-Archive -Path $DownloadDestination -DestinationPath (Get-Location)
          Remove-Item $DownloadDestination
        shell: pwsh

      - name: Check Tabular Editor Version
        run: |
          ./TabularEditor.exe -V
        shell: pwsh
