name: Power BI Dataset Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Power BI Build Job
    runs-on: windows-latest

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2. Initialize Variable (PBIDataset)
      - name: Initialize Variable
        run: echo "PBIDataset=${{ secrets.PBI_DATASET }}" >> $GITHUB_ENV

      # 3. Update JSON File
      - name: Update JSON File
        run: |
          $ArtifactPath = "$(Get-Location)\${{ env.PBIDataset }}"
          $JsonData = Get-Content $ArtifactPath | ConvertFrom-Json
          $UpdatedJson = $JsonData.createOrReplace.database
          $UpdatedJson | ConvertTo-Json -depth 32 | Set-Content $ArtifactPath
        shell: pwsh

      # 4. Download Tabular Editor
      - name: Download Tabular Editor
        run: |
          $TabularEditorUrl = "https://github.com/otykier/TabularEditor/releases/download/2.16.4/TabularEditor.Portable.zip"
          $DownloadDestination = Join-Path (Get-Location) "TabularEditor.zip"
          Invoke-WebRequest -Uri $TabularEditorUrl -OutFile $DownloadDestination
          Expand-Archive -Path $DownloadDestination -DestinationPath (Get-Location)
          Remove-Item $DownloadDestination
        shell: pwsh

      # 5. Generate BIM file from XMLA file
      - name: Generate BIM file using XMLA file
        run: |
          .\TabularEditor.exe "${{ github.workspace }}\${{ env.PBIDataset }}" -B "${{ github.workspace }}\Model.bim"
        shell: cmd

      # 6. Copy Pipeline Scripts
      - name: Copy Pipeline Scripts
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          cp -r Pipeline\ Scripts/* ${{ github.workspace }}/artifacts/
        shell: pwsh

      # 7. Run GitHub Security Scan (CodeQL)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: powershell

      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v2

      # 8. Upload the Power BI Dataset as an Artifact
      - name: Upload Power BI Dataset Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PowerBI-Dataset
          path: |
            ${{ github.workspace }}/Model.bim
            ${{ github.workspace }}/artifacts/
