name: Generate Bim file using XMLA file

on: [workflow_dispatch]

jobs:
  generate-bim:
    runs-on: windows-latest  # Ensure a Windows runner is used

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Checks out the repository

      - name: Generate Bim file using XMLA file
        shell: pwsh  # Specifies using PowerShell
        run: |
          # Generate Bim file using XMLA file
          $PBIDataset = ".\aa.xmla"
          $BimOutput = ".\Model.bim"
          $TabularEditor = "D:\a\WKEnablon_POC\WKEnablon_POC\TabularEditor.exe"

          # Run TabularEditor to generate .bim file
          $TabularEditor $PBIDataset -B $BimOutput
